### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by Codemaine** [Aslam97/react-fancy-switch#5]
Is there a way to add icons to each radio in the switch? If not, could you please implement this?

**Comment by Aslam97** [comment]
@Codemaine Now it support custom render, update to latest version v1.0.2 and take a look at this example https://github.com/Aslam97/react-fancy-switch/blob/9bd5506f7873e77c4e6e0ebb812de2d25ecc88ef/website/src/App.tsx#L161
